name: Release

on:
  push:
    tags:
      - "v[0-9]+.*"
    branches:
      - 'master'
      - 'android'

jobs:

  build-android:
    strategy:
      matrix:
        target:
          - aarch64-linux-android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          target: ${{ matrix.target }}

      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      - name: Build
        run: cargo ndk -t arm64-v8a build --target ${{ matrix.target }} --package lovely-android --release

      - name: Upload dobby artifact
        uses: actions/upload-artifact@v4
        with:
          name: libdobby.so
          path: ./crates/dobby-sys/dobby/build/android/arm64-v8a/libdobby.so
          if-no-files-found: error

      - name: Upload lovely artifact
        uses: actions/upload-artifact@v4
        with:
          name: liblovely.so
          path: ./target/aarch64-linux-android/release/liblovely.so
          if-no-files-found: error

      - name: Submit build artifact
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          gh release upload ${{ github.ref_name }} ./crates/dobby-sys/dobby/build/android/arm64-v8a/libdobby.so ./target/aarch64-linux-android/release/liblovely.so
